language: php

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    global:
        - secure: FJ1KrvGCSDjg/7RIGOZGTF+85SHuE4S2oD7vva2PP5pS9kg8gQN7xLqaW0UITpxufnkIEeOjpUXj3HNO1klibAdBR5TNa7Ntx9ilgmsYqiq0x8lNfs76xA/wNm455v+0SoDVP50isi2T6zo3/DMKJM1JwlJHRv47x2s/NIfvUK3qwxa26GRk5rYR9Cg6yYny+TEBXuXMI0ZPF5FNbpAbCvMBhopdoszyJWqdJGNyh0QlsW4cNsclrLzJKm2OaWyK7AU1TzmDAMXR+fzKb8K95kwwP06FCvTxJWlmHHsTdkBdmr0zqYv94F2XojeZu+lKkXR+jk3dEBqJfgbevsMtRjstFAy1sfBL1ql/cLEfpOGIRBSkq2pRF57tHeqqPIr2hC5Gs6hLJt+zYAqMhwB5aqcg4xidMEHPH0pCnoJBqqlqv2Wp+pia3jzuY4kJot/e+5Z1T2oVbj/KOGdsHX/8V75WOZPWOWM67klPPKlJTkKWXb60SjA0AxJTMe9mrTndKy8jjdAj3tlcs38rpfTysfiERa0JPRNvuuwdPCNQ9pL9X3rvu6/9vsz5yWqT0PgjYVn6PZvK2PJpsvxH6fJUBbFhm5xH3WIeqrPW6MyxpqBG8tPoSehwWwgp07qKO/yYOdPCcpzOZTOSXkqlkKCMeei0qdi+ymtnnokflcMFDzE=
        - secure: UtjH5GayiWwBO8VxrR/RUY1jyBy5p/WM9skMaVnliMuGGv9bvu37KYmPO8va3UNzUKBk4oVXubjb55CaUescwO0cto256hgQEm+pkbiqIRvwFbKFU/pp8zfHXnWBhlB7ndxtrCFrS4zhpA0KRQezFYhSD/zYKIDfBIDsoyAcOoQM6u30oy3E1LemMMoHkZKfUGt+nj+X+2iD0hZXF+RgVhVw38ptN5jPy9eGQyAnXzKlOhRdrsYekIu3rwtqpdG/fhLe4Ex8nlE8CgaMzM2iWt9zzcVwfJdT+VWYWcanRaQQrCwYeOors67gWHhFHlxd9BhITxpY99+SdeMsBZzn01SGHpcbQ3WL29zYsdSbErV0jXuJmhpRh9AhZZiUUnsPZGLX8zIJg9E1NSt9/ZWoOYqiwl81yBDINbRGaI2w4ucnXXt8mJXQQpiT+FH7Bhq9eROQBWgOdH2FrKpVvm8k4ce45RuyhV/YFYK6XrhuqWHTvPK2ZPs7Vl7MGAuFXYW+rPrIXeX7XX/TosbdUGJXFKHaAKhIbUrf6JpMXND59iAbu47SvN8yv4e7UjMvfaRcDOe3zyFWufwuzncnXP/wJHZeGrwvgm5cqxKouepm6sp8uc4UnYP1PnMI6koRcZTPpkBOYZZpYoP9GXAwqgev7zblzHAL43ijgoqa6vcgP2o=
        - secure: HG5ldJtIlJlzuD6ccz7sxZ4LVuzcPzaZI/+JknkdsI4MYgOhcJYh7ms0MRq7ZoVoZZu8lZk3kyWrKpJQubwr1+FrHlGFGbiAy7bqfL3zCubPfQIQ77AW6UiL2MHYl0UGIWda6oDnec60Qld20ywK6V0qQPIlI3CULZSStj/17Ptz0jlb42+qEb0a3lAthAjrAjjIy9Q2J0X5nZQ7bGDXS0gNS/rgq5dd0xVgg2x+8kKJ+cqrnhFqV5H7SVj3YGoprOGXKwfrL6To2OHj4Wba9coHJJ7XUXFJlfPKmEJihRTRnCoiCXtrgoQxbHpJ6pZSg2TTMo2XPHi+9qIWPzxeBzZUH3951NFnUF7ZRJ7B6jBvArJ2jeIFccfKyPwzyvgv2YRv7gB/vM621bruoqrRsRmpZ4Qn93n3GuUlICs1z1EPYkw3Mmrvbgb1QP0Q2/4haLmkb0dc+w6IoD2tPcr9PmyL7aATavnonFYbTsdy/LLfTys/6SOwJm+br1L/p3d9qdgB05/K1DSpkjrFSjmeG3CBqvdOClihxdaD/w5KY/BJCY/V6/K+Oi92fIhkfRR+qavS8GgjGYqPoZizY2KWuViVpuMlEgkblbnGHpkyZuPnzQB9OGWt60vxY/Q/Th1oe9La7EASuU7gG+wI91PnVT9wZ7VC0swoGEu8vshxetE=
        - secure: rx6qs1Wrt174JFE5l3GfmbMfjJ24ipNGeGU8Gg/oii4ONBSAuMorNOvkbG9NhqlwUuRJYi4/ftiphSKqyYOiEuemejoXNIE4IsWFL9I6hYNgh9z7Nzuxbg5nLYIH5GWVMMdUIjmsYL1wLNFqQISqbGMvNzgM81M+Icl2FtnoJOJbc+TL0ci2cjHC1WWMdkdzlNlTYoUvVDzYOrzaQsb2PDmqTc8SU/2DFTzcysWSyvkKUhNRnJN3a3X2D7azoWIIVjsSiURwhd4JseFF1T1xrZTkyoPEKxu+i8P+1fn96zAeOArsIq5Ktge70yaUkOvf6qAgd7+0vWVMke/RcMRRJWDm+q9J444jp+WEHeg61xxNOkhoGDjhC9cgeXBkp1hh4q/VAelPJ8FzaehgOLqqfUb4xH3LF0/xUtQhbSTwU+YPgK1BsUxhKKFwrwPPPs5uSuZB7fm39ytHq+PK6hFp309RJEuV2hrvYYL5fjLgoOktIDeaxmjURpSH5ViRJRZYFXobL1XeycopkR48EL/ORWl+b48hN5ubsPpR/KqFpOBJ9WsN5sDCZ233o5AGYNgCnpo+8NeqJRQgpRVxVseOoGI9BMU4zZNY4Su6Cfv9yLMHY5KPwwVExXIhRVw8YihhYj5Ra3M3OAbiNGCdQjuUcfCLb4KZ97fO9JbrLeKe83E=
        - secure: xRJIICK6DG7vV2ik0q+itj3M/UT32bIS2rjuSE6gROUzqkXFTk0s/Yp5tGamTXf8E8Nkv2ngbhpYSrXCGgx/GIvHeXHCuAdevicRwMGl47nINGJTZ1uzrKT026AdGgW2DQuJUdFSl5K6teDPaApUg0yVmI0z0sZP0lo6voCWHbA7v5OR8odqD5O6EhKuB7amECYHnAsRbbRxvbYVb2J09sMZmZ/xSeHMYpSMH9ldyeoM7AqAvNrJnEzXN5D+BXn1nJ92JXsrQbwisJ/bMlIjLt5C49z5OL43YrRqTFjT3BBS3chVX+cxEjq4u5sNyO6c7QiP2d++EzimL/8GTh9B4VAx3VzzvNSTlUSzfclWCwH69ejHfaBvIApN+MqqFtB5eN0NlAPdw22exDX/1qghpEe7xGn1RjoQQgeNULThjRshVGXyPHzXtjMZhFveUKvXHkVz81DLfkR1MBr/UcUIgRzrc0RRtT6+H8YqFrryFIGStxlgysDSg9sqBKucVqkyOTGawyWHfC1IqQrDrw1dlnGWdQAcZ9cU2whY2yzrcD1a1WyT5e/Or6msb+J9zY0g36eiwWZDBHcQ2Q1VjXaTCiwPH50/gbgPgG1CX5mmQIgbe8puAlxsfuw2vCOv/YN5bZLUY8GyF4ceZKGq1ZDmnt2Bx9XCTdPH/+6MNaRcTrg=
    matrix:
        - COMPOSER_FLAGS="--prefer-lowest"
        - COMPOSER_FLAGS=""

jobs:
    allow_failures:
        - php: nightly

php:
    - nightly
    - 8.0
    - 7.4
    - 7.3
    - 7.2
    - 7.1
    - 7.0

before_script:
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - phpenv config-rm xdebug.ini
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - composer test

after_script:
    - composer upload-coverage
